# coding: utf-8

"""
    CeoCLOUD

    CeoCLoud Api Documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.iot_api import IotApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIotApi(unittest.TestCase):
    """IotApi unit test stubs"""

    def setUp(self):
        self.api = IotApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_iot_statechange_device_state_post(self):
        """Test case for iot_statechange_device_state_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
