# coding: utf-8

"""
    CeoCLOUD

    CeoCLoud Api Documentation  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login_post(self):
        """Test case for login_post

        login a user.  # noqa: E501
        """
        pass

    def test_logout_get(self):
        """Test case for logout_get

        logout user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
